### ISSUE TITLE
Docs update

### ISSUE THREAD

**Issue by masimao** [flaviosilveira/Jquery-Price-Format#43]
Hi,

Would be great if you update the documentation, i found the option `clearOnEmpty` directly in the code.

The plugin is very nice!

**Comment by flaviosilveira** [comment]
I will transfer all documentation and examples from jquerypriceformat.com for GitHub Pages.
I will also improve the texts.

Thanks.

**Comment by flaviosilveira** [comment]
Done Guys!
http://flaviosilveira.com/Jquery-Price-Format/

**Comment by podrivo** [comment]
Hey @flaviosilveira, you forgot to update the following:

- "Example 5 - Working with limits" is using `clearPrefix` as an example;
- "Example 6 - Clear Prefix and Suffix on Blur" has no `clearSuffix`, only `clearPrefix` in the example.
- Example word in example 8 and 9 is still in Portuguese.
- Customizable and Maintenance are typos at the beginning

**Comment by podrivo** [comment]
Related: https://github.com/flaviosilveira/Jquery-Price-Format/issues/60
